### ISSUE TITLE
Fails on non-square images

### ISSUE THREAD

**Issue by stasoid** [DylanMeeus/ImageF-ck#1]
In function `read_pixels_as_brainfuck`:
`image.size[0]` - width (number of columns); `image.size[1]` - height (number of rows)
So instead of 
```
        for r in range(image.size[0]):
            for c in range(image.size[1]):
```
it should be
```
        for r in range(image.size[1]):
            for c in range(image.size[0]):
```

**Comment by DylanMeeus** [comment]
Thank you. I will take a look at this over the weekend ;-)

**Comment by DylanMeeus** [comment]
I forgot about this, but made some changes to the interpreter and was reminded of your comment by doing so.

I have updated the [code](https://github.com/DylanMeeus/ImageF-ck/commit/c03396b35d21a3dab82e3e16958c27532cb4738a)

Thanks for pointing that out!
